### ISSUE TITLE
Spammy rate limit errors in the log

### ISSUE THREAD

**Issue by GlacierWalrus** [filecoin-station/core#337]
Running the docker image to test it out and I'm getting a lot of 403s with a rate limit warning.

Are there any docs on tuning this in station config so I'm not hammering github?

```
Failed to download spark source. Retrying...
[voyager]  ⇣ checking for updates
Error: Cannot fetch filecoin-station/voyager latest release: 403
{"message":"API rate limit exceeded for xxx.xxx.xxx.xxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_ur
l":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

    at getLatestDistTag (file:///usr/src/app/lib/modules.js:108:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async updateSourceFiles (file:///usr/src/app/lib/modules.js:144:19)
    at async RetryOperation._fn (file:///usr/src/app/node_modules/p-retry/index.js:57:20) {
  attemptNumber: 8,
  retriesLeft: 3
}
```

**Comment by juliangruber** [comment]
Please update to the latest version, this has already been fixed
