### ISSUE TITLE
Core getting stuck

### ISSUE THREAD

**Issue by zipiju** [filecoin-station/core#392]
Core gets stuck and only restart resumes the normal operation. The last log entry when this happens is the following:

```
node --version
v20.11.0
```

```
/usr/bin/station -v
@filecoin-station/core: 20.1.11
```

```
[2024-04-03T05:18:05Z INFO  module:voyager/main] Prod benchmark successful!
[2024-04-03T05:18:05Z INFO  module:voyager/main] Running prod benchmark...
[2024-04-03T05:18:05Z INFO  module:voyager/main] Testing /ipfs/bafkreid7wy3cjoxe4lu7h33luzxsotccaumkbbeouramc37m7avpy6r5kq...
{
  "totalJobsCompleted": 15667,
  "rewardsScheduledForAddress": "0.0094616700749552"
}
[2024-04-03T05:18:06Z INFO  module:voyager/main] Prod benchmark successful!
[2024-04-03T05:18:06Z INFO  module:voyager/main] Running prod benchmark...
[2024-04-03T05:18:06Z INFO  module:voyager/main] Testing /ipfs/QmY6mtSfYZRLmLTJeoV8P9Y3VQTbqF7SA9ZEXvtmWA5pyR/hidden_1080_30fps.gif...
{
  "totalJobsCompleted": 15668,
  "rewardsScheduledForAddress": "0.0094616700749552"
}
[2024-04-03T05:18:07Z ERROR module:voyager/main] Failed to fetch content {
      cause: "All attempts to fetch content have failed. Last error: The signal has been aborted"
    }
[2024-04-03T05:18:07Z INFO  module:voyager/main] Prod benchmark successful!
[2024-04-03T05:18:07Z INFO  module:voyager/main] Running prod benchmark...
[2024-04-03T05:18:07Z INFO  module:voyager/main] Testing /ipfs/QmTLTtjLCgUeCxxBVdr3Rvr185o6PGhmxvtyDwPehe3qd5...
{
  "totalJobsCompleted": 15669,
  "rewardsScheduledForAddress": "0.0094616700749552"
}
[2024-04-03T05:18:08Z ERROR module:voyager/main] Failed to fetch content {
      cause: "All attempts to fetch content have failed. Last error: The signal has been aborted"
    }
[2024-04-03T05:18:08Z INFO  module:voyager/main] Prod benchmark successful!
[2024-04-03T05:18:08Z ERROR zinniad] DOMException: The signal has been aborted
        at new DOMException (ext:deno_web/01_dom_exception.js:115:20)
        at AbortSignal.[[[signalAbort]]] (ext:deno_web/03_abort_signal.js:134:14)
        at AbortController.abort (ext:deno_web/03_abort_signal.js:279:30)
        at AbortSignal.<anonymous> (file:///home/filstation/.cache/filecoin-station-core/sources/voyager/vendor/saturn-js-client/dist/strn.min.js:2:811255)
        at innerInvokeEventListeners (ext:deno_web/02_event.js:755:7)
        at invokeEventListeners (ext:deno_web/02_event.js:802:5)
        at dispatch (ext:deno_web/02_event.js:659:9)
        at AbortSignal.dispatchEvent (ext:deno_web/02_event.js:1044:12)
        at AbortSignal.[[[signalAbort]]] (ext:deno_web/03_abort_signal.js:145:11)
        at AbortController.abort (ext:deno_web/03_abort_signal.js:279:30)
[4/3/2024, 5:18:08 AM] INFO  Voyager exited with code: 1
[4/3/2024, 5:18:08 AM] ERROR Voyager crashed with exit code 1
[4/3/2024, 5:18:09 AM] INFO  Spark exited via signal SIGTERM
{
  "totalJobsCompleted": 15670,
  "rewardsScheduledForAddress": "0.0094616700749552"
}
```

**Comment by juliangruber** [comment]
I can confirm this issue and that I'm actively working on a fix 👍

**Comment by ricarper** [comment]
> I can confirm this issue and that I'm actively working on a fix 👍

Here, freeze until now since 2:48:13 PM
The solution for me is to restart the container every hour.

[4/3/2024, 2:48:13 PM] INFO  Voyager exited with code: 1
[4/3/2024, 2:48:13 PM] ERROR Voyager crashed with exit code 1
Reporting the poblem to Sentry for inspection by the Station team.
[4/3/2024, 2:48:13 PM] INFO  Spark exited via signal SIGTERM

**Comment by c0ldcertified** [comment]
also seeing 'failed to get contract address'

**Comment by zipiju** [comment]
Since update to 20.1.13 yesterday the station experienced no hangups, at least the Linux node.js version. I believe this can be marked as fixed. Thank you.

**Comment by juliangruber** [comment]
@c0ldcertified please use this issue only for core getting stuck, not other errors. If you would like to discuss them, please open a separate issue

**Comment by juliangruber** [comment]
> Since update to 20.1.13 yesterday the station experienced no hangups, at least the Linux node.js version. I believe this can be marked as fixed. Thank you.

My instance also hasn't got stuck since. Great!
