### ISSUE TITLE
meridian error

### ISSUE THREAD

**Issue by csmasterpath2023** [filecoin-station/core#484]
With [nodejs](https://nodejs.org) installed, you can check the contract balance yourself:

```bash
$ npx meridian available-balance --address 0x8460766Edc62B525fc1FA4D628FC79229dC73031
34.418694628501832271 FIL
```

_Originally posted by @juliangruber in https://github.com/filecoin-station/core/issues/455#issuecomment-2104574510_

**Comment by csmasterpath2023** [comment]
~~~
0 verbose cli /home/cs144/.nvm/versions/node/v20.13.1/bin/node /home/cs144/.nvm/versions/node/v20.13.1/lib/node_modules/npm/bin/npm-cli.js
1 info using npm@10.5.2
2 info using node@v20.13.1
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 0ms
5 timing config:load:file:/home/cs144/.nvm/versions/node/v20.13.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/cs144/mer/node_modules/meridian/.npmrc Completed in 1ms
10 timing config:load:project Completed in 16ms
11 timing config:load:file:/home/cs144/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/cs144/.nvm/versions/node/v20.13.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 19ms
17 timing npm:load:configload Completed in 19ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 1ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm exec meridian available-balance --address 0x8460766Edc62B525fc1FA4D628FC79229dC73031
22 verbose argv "exec" "--" "meridian" "available-balance" "--address" "0x8460766Edc62B525fc1FA4D628FC79229dC73031"
23 timing npm:load:setTitle Completed in 1ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/cs144/.npm/_logs/2024-05-23T10_55_59_251Z-
26 verbose logfile /home/cs144/.npm/_logs/2024-05-23T10_55_59_251Z-debug-0.log
27 timing npm:load:logFile Completed in 1ms
28 timing npm:load:timers Completed in 1ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 40ms
31 silly logfile done cleaning log files
32 timing arborist:ctor Completed in 1ms
33 timing command:exec Completed in 18ms
34 verbose stack Error: could not determine executable to run
34 verbose stack     at getBinFromManifest (/home/cs144/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/libnpmexec/lib/get-bin-from-manifest.js:17:23)
34 verbose stack     at exec (/home/cs144/.nvm/versions/node/v20.13.1/lib/node_modules/npm/node_modules/libnpmexec/lib/index.js:188:15)
34 verbose stack     at async module.exports (/home/cs144/.nvm/versions/node/v20.13.1/lib/node_modules/npm/lib/cli-entry.js:61:5)
35 verbose pkgid meridian@1.0.1
36 verbose cwd /home/cs144/mer/node_modules/meridian/src
37 verbose Linux 6.5.0-35-generic
38 verbose node v20.13.1
39 verbose npm  v10.5.2
40 error could not determine executable to run
41 verbose exit 1
42 timing npm Completed in 230ms
43 verbose code 1
44 error A complete log of this run can be found in: /home/cs144/.npm/_logs/2024-05-23T10_55_59_251Z-debug-0.log
~~~

**Comment by juliangruber** [comment]
Sorry, that should have been

```
$ npx @meridian-ie/cli available-balance --address 0x8460766Edc62B525fc1FA4D628FC79229dC73031
34.418694628501832271 FIL
```
