### ISSUE TITLE
Failed to download spark source

### ISSUE THREAD

**Issue by liualxie** [filecoin-station/core#494]
Failed to download spark source. Retrying...
[5/31/2024, 12:43:09 AM] ERROR Failed to download latest Zinnia module source code
Usage: station.js [options]

Options:
  -j, --json          Output JSON                                      [boolean]
      --experimental  Also run experimental modules                    [boolean]
  -v, --version       Show version number                              [boolean]
  -h, --help          Show help                                        [boolean]

Error: Invalid block bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe of root bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe
    at Object.get (file:///usr/src/app/lib/modules.js:199:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19) {
  attemptNumber: 11,
  retriesLeft: 0,
  [cause]: TypeError: Cannot read properties of undefined (reading 'cid')
      at validateBlock (file:///usr/src/app/node_modules/@web3-storage/car-block-validator/esm/src/index.js:56:36)
      at Object.get (file:///usr/src/app/lib/modules.js:197:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19)
}
This has been 12 hours and still hasn't been running properly, and I have deleted the original Docker and downloaded it again, but it still hasn't been resolved.

**Comment by liualxie** [comment]
The new nodes are unable to function properly due to this error, and the rewards for the old nodes are not increased. Starting from yesterday's update.

**Comment by liualxie** [comment]
This is a random error that occurs in approximately 3 out of 10 nodes. Due to this error, the nodes will automatically stop and the Docker will automatically shut down, preventing it from continuing normally.

**Comment by liualxie** [comment]
[6/1/2024, 12:50:18 PM] INFO  Updating source code for Zinnia modules...
[voyager]  ⇣ checking for updates
[voyager]  ✓ no update available
[spark]  ⇣ downloading source files via https://bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe.ipfs.w3s.link?format=car
Error: Invalid block bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe of root bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe
    at Object.get (file:///usr/src/app/lib/modules.js:199:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19) {
  attemptNumber: 1,
  retriesLeft: 10,
  [cause]: TypeError: Cannot read properties of undefined (reading 'cid')
      at validateBlock (file:///usr/src/app/node_modules/@web3-storage/car-block-validator/esm/src/index.js:56:36)
      at Object.get (file:///usr/src/app/lib/modules.js:197:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19)
}
Failed to download spark source. Retrying...
[spark]  ⇣ downloading source files via https://bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe.ipfs.w3s.link?format=car
Error: Invalid block bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe of root bafkreihkjmnqhej5dynwfhpu4ii4voctfcsdde3i2lnycnx2lkvap7leqe
    at Object.get (file:///usr/src/app/lib/modules.js:199:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19) {
  attemptNumber: 2,
  retriesLeft: 9,
  [cause]: TypeError: Cannot read properties of undefined (reading 'cid')
      at validateBlock (file:///usr/src/app/node_modules/@web3-storage/car-block-validator/esm/src/index.js:56:36)
      at Object.get (file:///usr/src/app/lib/modules.js:197:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19)
}
Failed to download spark source. Retrying...

**Comment by juliangruber** [comment]
This should be fixed now
