### ISSUE TITLE
Failed to download spark source. Retrying...

### ISSUE THREAD

**Issue by renarios** [filecoin-station/core#552]
I receive many errors on my Filestation docker:

`Failed to download spark source. Retrying...
[spark]  ⇣ downloading source files via https://bafkreide6ko2zyfckayhfbzdrovcuccfnwhuu3wigtsrfhzftjnbdglemi.ipfs.w3s.link?format=car
Error: Invalid block bafkreide6ko2zyfckayhfbzdrovcuccfnwhuu3wigtsrfhzftjnbdglemi of root bafkreide6ko2zyfckayhfbzdrovcuccfnwhuu3wigtsrfhzftjnbdglemi
    at Object.get (file:///usr/src/app/lib/modules.js:199:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19) {
  attemptNumber: 7,
  retriesLeft: 4,
  [cause]: TypeError: Cannot read properties of undefined (reading 'cid')
      at validateBlock (file:///usr/src/app/node_modules/@web3-storage/car-block-validator/esm/src/index.js:56:36)
      at Object.get (file:///usr/src/app/lib/modules.js:197:17)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async resolve (file:///usr/src/app/node_modules/ipfs-unixfs-exporter/dist/src/resolvers/raw.js:22:19)
}
Failed to download spark source. Retrying...
`
How can I resolve this issue?

**Comment by juliangruber** [comment]
https://github.com/filecoin-station/core/pull/553

**Comment by renarios** [comment]
Thanks for the update. I'm kind of lost in #553 and don't know what to do.

**Comment by juliangruber** [comment]
Ah sorry, there's nothing to do for you atm, it will either fix itself or an update of Station Core will be rolled out
