### ISSUE TITLE
AssertionError: Values are not equal: stationId must be a string

### ISSUE THREAD

**Issue by renarios** [filecoin-station/core#638]
I get these errors on the filestation docker

```
[2024-12-02T22:55:05Z INFO  module:spark/main] Sleeping for 60 seconds before starting the next task...
[2024-12-02T22:56:05Z INFO  module:spark/main]
[2024-12-02T22:56:05Z INFO  module:spark/main] Checking the current SPARK round...
[12/2/2024, 10:56:05 PM] INFO  SPARK retrieval reporting resumed
[2024-12-02T22:56:05Z INFO  module:spark/main] Fetching round details at location /rounds/meridian/0xxxx0766edc6xxxfc1fxxx628fxxx229dxxx31/20555
[2024-12-02T22:56:05Z INFO  module:spark/main] Current SPARK round: { roundId: "25979", startEpoch: "4495764" }
[2024-12-02T22:56:05Z INFO  module:spark/main]   17 max tasks per round
[2024-12-02T22:56:05Z INFO  module:spark/main]   1133 retrieval tasks
[2024-12-02T22:56:05Z INFO  module:spark/main]   randomness: xxxa75d2f0802xxx8e1d2exxxa432dexxx2f1940xxxd7931xxx3f62xxx3cb
[12/2/2024, 10:56:05 PM] ERROR SPARK failed reporting retrieval
[2024-12-02T22:56:05Z ERROR module:spark/main] AssertionError: Values are not equal: stationId must be a string


        [Diff] Actual / Expected


    -   undefined
    +   string


        at assertEquals (ext:zinnia_runtime/vendored/asserts.bundle.js:532:11)
        at pickTasksForNode (file:///home/node/.cache/filecoin-station-core/sources/spark/lib/tasker.js:130:3)
        at Tasker.#updateCurrentRound (file:///home/node/.cache/filecoin-station-core/sources/spark/lib/tasker.js:81:39)
        at eventLoopTick (ext:core/01_core.js:178:11)
        at async Tasker.next (file:///home/node/.cache/filecoin-station-core/sources/spark/lib/tasker.js:44:5)
        at async Spark.getRetrieval (file:///home/node/.cache/filecoin-station-core/sources/spark/lib/spark.js:40:23)
        at async Spark.nextRetrieval (file:///home/node/.cache/filecoin-station-core/sources/spark/lib/spark.js:189:23)
        at async Spark.run (file:///home/node/.cache/filecoin-station-core/sources/spark/lib/spark.js:208:9)
        at async file:///home/node/.cache/filecoin-station-core/sources/spark/main.js:4:1 {
      name: "AssertionError"
    }
[2024-12-02T22:56:05Z INFO  module:spark/main] Sleeping for 60 seconds before starting the next task...
```
Any idea how to solve this?

**Comment by bajtos** [comment]
@renarios Thank you for reporting the issue. 
- Could you please share the command you used to start the Station docker container, including the configuration of environment variables? (Feel free to redact the values like the wallet address.) 
- Also, please share the logs from Station Core start (again, feel free to redact any sensitive information). 
- What is the image version you are running? Was Station Core working for you before, or is this a new instance?
